upstream geozones_app {
    server web:5000;
    keepalive 16;
}

server {
    listen 80;
    server_name geozones.wrds361.com;
    client_max_body_size 160M;

    resolver 127.0.0.11 valid=10s;

    location /uploads/ {
        alias /app/uploads/geozones/;
        expires 1d;
    }

    location / {
        proxy_pass         http://geozones_app;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_read_timeout 60s;
    }
}
